export interface Player {
  shirtNumber: number;
  name: string;
  surname: string;
  nickname?: string;
  nationality: Flag;
  position: Position;
  overall: number;
  seasonStats: SeasonStats;
  teamId: number;
}

interface SeasonStats {
  goals: number;
  assists: number;
  injured: number;
}

export enum Position {
  POR = 'POR',
  DF = 'DF',
  LD = 'LD',
  LI = 'LI',
  MC = 'MC',
  MCD = 'MCD',
  MCO = 'MCO',
  ED = 'ED',
  EI = 'EI',
  DC = 'DC',
}

export enum Flag {
  Albania = 'al',
  Andorra = 'ad',
  Angola = 'ao',
  Argelia = 'dz',
  Argentina = 'ar',
  Australia = 'au',
  Austria = 'at',
  Belgium = 'be',
  Bolivia = 'bo',
  Bosnia = 'ba',
  Brazil = 'br',
  Bulgaria = 'bg',
  BurkinaFaso = 'bf',
  CaboVerde = 'cv',
  Cameroon = 'cm',
  Canada = 'ca',
  Chile = 'cl',
  China = 'cn',
  Colombia = 'co',
  CongoDR = 'cd',
  CostaRica = 'cr',
  Croatia = 'hr',
  Cyprus = 'cy',
  CzechRepublic = 'cz',
  Denmark = 'dk',
  DominicanRepublic = 'do',
  Ecuador = 'ec',
  Egypt = 'eg',
  England = 'gb-eng',
  Estonia = 'ee',
  FaroeIslands = 'fo',
  Finland = 'fi',
  France = 'fr',
  Gambia = 'gm',
  Georgia = 'ge',
  Germany = 'de',
  Ghana = 'gh',
  Greece = 'gr',
  Guinea = 'gn',
  GuineaBissau = 'gw',
  GuineaEquatorial = 'gq',
  Honduras = 'hn',
  Hungary = 'hu',
  Iceland = 'is',
  Iran = 'ir',
  Iraq = 'iq',
  Ireland = 'ie',
  Israel = 'il',
  Italy = 'it',
  IvoryCoast = 'ci',
  Jamaica = 'jm',
  Japan = 'jp',
  Kosovo = 'xk',
  Latvia = 'lv',
  Liechtenstein = 'li',
  Lithuania = 'lt',
  Luxembourg = 'lu',
  Macedonia = 'mk',
  Mali = 'ml',
  Mexico = 'mx',
  Moldavia = 'md',
  Montenegro = 'me',
  Morocco = 'ma',
  Mozambique = 'mz',
  Netherlands = 'nl',
  NewZealand = 'nz',
  Nigeria = 'ng',
  Norway = 'no',
  Panama = 'pa',
  Paraguay = 'py',
  Peru = 'pe',
  Poland = 'pl',
  Portugal = 'pt',
  Qatar = 'qa',
  Romania = 'ro',
  Russia = 'ru',
  SaudiArabia = 'sa',
  Scotland = 'gb-sct',
  Senegal = 'sn',
  Serbia = 'rs',
  SierraLeona = 'sl',
  Slovakia = 'sk',
  Slovenia = 'si',
  SouthAfrica = 'za',
  SouthKorea = 'kr',
  Surinam = 'sr',
  Spain = 'es',
  Sweden = 'se',
  Switzerland = 'ch',
  Togo = 'tg',
  Tunisia = 'tn',
  Turkey = 'tr',
  Ukraine = 'ua',
  UnitedStates = 'us',
  Uruguay = 'uy',
  Uzbekistan = 'uz',
  Venezuela = 've',
  Wales = 'gb-wls',
  Zambia = 'zm',
  Zimbabwe = 'zw',
}
